### PR TITLE
Refactor based on rasterise()

### PR DESCRIPTION
**Pull request by evanbiederstedt**
* Major refactor we discussed

### CODE REVIEW

**Comment by VPetukhov** [comment]
Hi @evanbiederstedt ,
Thanks for the refactoring! You mistakenly removed all code from `geom_boxplot_jitter`. It's not just a geom_boxplot, but also allowed to jitter outlier points. Could you please fix that?
And it definitely should be version 0.2 now.

**Comment by evanbiederstedt** [comment]
Thanks @VPetukhov---I knew there would be mistakes last night :)

I think this solution works, though it's not very pretty. 

* I think the vignettes have been updated appropriately. 
* I also added ` geom_violin_rast()`, because we might as well resolve this issue: https://github.com/VPetukhov/ggrastr/issues/8

There are probably a few more errors in this PR, but I'll have to do another closer look later. 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Once I finish the vignettes, this should be ready for review. 

It should resolve these issues as well:
https://github.com/VPetukhov/ggrastr/issues/4
https://github.com/VPetukhov/ggrastr/issues/8

**Comment by evanbiederstedt** [comment]
I think this should be ready for review @VPetukhov 

Let me know if there's anything else I can do on this front.

**Comment by evanbiederstedt** [comment]
We can merge here, and re-visit with `develop->master` if needed.

**Comment by VPetukhov** [comment]
That was the right decision. Thank you so much!

**Pull request merged**
