### PR TITLE
Use polymorphism for rasterise()

### PR DESCRIPTION
**Pull request by evanbiederstedt**
Trying out Viktor's idea here: https://github.com/VPetukhov/ggrastr/issues/29

I haven't fully tested this out, so I'll keep it in draft. 

It seems to work: 
```
library(ggrastr)
library(ggplot2)
rasterise(ggplot(pressure, aes(temperature, pressure)) + geom_line())
rasterize(ggplot(pressure, aes(temperature, pressure)) + geom_line())
rasterize(ggplot(pressure, aes(temperature, pressure)))
ggplot(pressure, aes(temperature, pressure)) + rasterize(geom_line())
```

### CODE REVIEW

**Comment by evanbiederstedt** [comment]
Yeah, the CI/CD tests are failing, as we're getting stuck on whether the inputs are a list....

I'm leaning towards concluding we're over-engineering this. Maybe it's best to close the issue and concentrate on other things :) CC @VPetukhov

**Comment by VPetukhov** [comment]
Soon I'll be finalizing our figures for Cacoa, and there I'd very much want to have this functionality. So I'll check this PR and see if I can fix the CI. Worst case scenario, we can drop polymorphism and just give a different name to the function, e.g. `rasterise_plot`, perhaps?

**Comment by evanbiederstedt** [comment]
We basically need to figure out how to deal with lists as inputs. 

We could it with the polymorphism, of course...

Maybe a new function is the right approach though, as this is getting a bit complicated

**Comment by VPetukhov** [comment]
Wait, but what is the problem there? Why can't we just check if the input is list and call the old implementation in this case?

**Comment by evanbiederstedt** [comment]
We need to:
--- check if it's a list
--- check that the items in the list are relevant. If not, thrown error. 
--- check if items are layers or ggplot2. If layers, then use the original function (without list code inside). If ggplot2, then use the ggplot2 function

**Comment by VPetukhov** [comment]
Got it, thanks. Well, then I'd suggest we use python-style polymorphism, where we don't rely on S3 at all, but instead create a couple of internal functions like `rasterise_plot` and `rasterise_layer` plus a routing function `rasterise`, which checks all these conditions. What do you think?
I missed the point where you added list input. Is it actually useful? I never tried this stuff, and it looks overly complicated to me.

**Comment by evanbiederstedt** [comment]
> create a couple of internal functions like rasterise_plot and rasterise_layer plus a routing function rasterise, which checks all these conditions.

Yeah, that's the best way forward I suspect. I did this in S3 because I couldn't remember the "best approach" for this in R. 

You can see I'm basically using something like a routing function anyways for class `"gg"`....

Anyways, I can see this approach working

> I missed the point where you added list input. Is it actually useful? I never tried this stuff, and it looks overly complicated to me.

It was a PR from others. It made sense at the time. Version 0.2.3.

**Comment by VPetukhov** [comment]
Thanks for the explanation! I should be able to finish this later this week or the next one.

**Comment by evanbiederstedt** [comment]
Yeah, I might take a pass too. It's fairly straightforward I think.

**Pull request closed without merging**
