### PR TITLE
CRAN version 0.1.8

### PR DESCRIPTION
**Pull request by evanbiederstedt**
@VPetukhov 

This is the version 0.1.8 uploaded to CRAN. 

My goal is to merge this to master, and release version 0.1.8 on github.

Then, we can make the version with geom_jitter_rast as 0.1.9, and add this to CRAN. (Note: the version 0.1.8 on CRAN doesn't have this function).

Let me know if this makes sense. I think it makes sense to merge this to master, but I'm open to other arrangements. 

Please review

Thanks, Evan

EDIT: I probably should have squashed the commits into one, but I'm not terribly fussy about such things.

### CODE REVIEW

**Comment by VPetukhov** [comment]
Hi Evan,
Thanks so much for the PR! No worries about single commit at all.
Could you please update the Changelog for these changes? And also, do we need to enable integration with travis.ci for this repo?

**Comment by evanbiederstedt** [comment]
@VPetukhov 

Thanks, I added some comments to `CHANGELOG.md`. 

I think you need to enable the travis on your end.

**Comment by evanbiederstedt** [comment]
Thanks!

**Comment by VPetukhov** [comment]
> I think you need to enable the travis on your end.

Added that. Thanks!

**Pull request merged**
