### PR TITLE
version 0.1.9, added geom_jitter_rast

### PR DESCRIPTION
**Pull request by evanbiederstedt**
And now the idea is to make this version 0.1.9, with `geom_jitter_rast`.

I'll then release this version, and update to CRAN. 

Note the only reason I did things this (somewhat complicated) way is `geom_jitter_rast` wasn't in the version 0.1.8, which I started to upload to CRAN.

I think we can merge to develop, and then develop -> master. 

As always, make any changes you wish :)

### CODE REVIEW

**Comment by evanbiederstedt** [comment]
After this, the goal is to release 0.1.9, and upload to CRAN. I suspect there should be no changes necessary to be CRAN friendly, but we'll see.

**Comment by VPetukhov** [comment]
Thanks! Was it intentional not to update the DESCRIPTION version in this PR?

**Comment by evanbiederstedt** [comment]
> Was it intentional not to update the DESCRIPTION version in this PR?

Nope, that was an error on my part :)

Changed now.

**Comment by VPetukhov** [comment]
Thanks!

**Comment by evanbiederstedt** [comment]
Thanks
I'll try to upload to CRAN. If it works, we can merge to master.

**Comment by evanbiederstedt** [comment]
The updated version 0.1.9 does work for CRAN: https://cran.r-project.org/web/packages/ggrastr/index.html

However, I would like to improve the vignettes and README a bit before releasing. There will be other PRs to address this.

**Pull request merged**
